config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts, only: [:new,:create,:index, :show]
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root  'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  before_create :create_remember_token
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  has_many :posts

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token)
  end

  def remember
    self.remember_token = User.new_remember_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_remember_token
    self.remember_token = User.new_remember_token
    self.remember_digest = User.digest(remember_token)
  end

  def decrypt(token)
    return false if token.nil?

    remember = Digest::SHA1.hexdigest(token)
    remember_digest == remember
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def loged_in?
    current_user
  end

  def current_user
    return nil unless cookies.signed[:user_id]

    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :signed_in_only!, only: %i[new create]

  def new
    @post = Post.new
  end

  def index
    @post = Post.all
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
    else
      flash[:danger] = 'Post NOT created'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def signed_in_only!
    redirect_to sign_in_path unless logged_in?
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  include ::SessionsHelper

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      remember(user)
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
    puts cookies.signed[:remember_token]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      permanent_user
      remember(@user)
      flash[:success] = 'Welcome new user!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = permanent_user
    puts @user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def user_in(post)
    logged_in? ? post.user.name : (link_to 'Login', login_path)
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    user ||= User.find_by(id: cookies.signed[:user_id])

    log_in(user) if user&.decrypt(cookies.signed[:remember])
    @current_user = user
    # if (user_id = session[:user_id])
    # @current_user ||= User.find_by(id: user_id)
    # elsif cookies[:remember_token]
    # #TSE changes @current_user=User.find_by(id: cookies.signed[:user_id])
    # end
  end

  def permanent_user
    @current_user = User.find_by(id: cookies.signed[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    # user.create_remember_token
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent.signed[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:remember_token)
    cookies.delete(:user_id)
  end

  def log_out
    forget(current_user)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_header.html.erb
<header class="navbar cnav">
  <div class="container">
    <%= link_to "SAMPLE APP", root_path, id: "logo" %>
    <nav>
      <ul class="nav">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <%= current_user.name %>
          <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Posts", new_post_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>SECRET POSTS</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @post.each do |article| %>
    <tr>
      <td><%= user_in(article) %></td>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'Show', post_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<% if !flash.empty? %>
    <div id="flash">
      <% flash.keys.each do |k| %>
          <div class="<%= k %>">
            <%= flash[k] %>
          </div>
      <% end %>
    </div>
<% end %>
<%= form_for @post do |f| %>
  <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.submit "Save Post" %>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p><p>
  <strong>Text:</strong>
  <%= @post.body %>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/index.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
  </tr>
  <% @users.each do |item| %>
      <% if logged_in? %>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= item.name %>
            </td>
            <td>
              <%= item.email %>
            </td>
          </tr>
      <% else %>
          <tr>
            <td>
          <%= link_to 'Login', login_path %>
            </td>
            <td>
              <%= link_to 'Login', login_path %>
            </td>
            <td>
              <%= link_to 'Login', login_path %>
            </td>
          </tr>
      <% end %>

  <% end %>

</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1><div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>      <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>      <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>      <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>      <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<table>
  <tr>
    <th>Usuario</th>
    <th>Nombre</th>
    <th>Email</th>
  </tr>
      <tr>
      <td>  <%= @user.name %> </td>
        <td>  <%= @user.email %> </td>
        <td>  <%= @user.password_digest %> </td>
      </tr>
</table>